#!/bin/sh
#
# Start the network....
#

case "$1" in
  start)
 	echo "Starting network..."
	/sbin/ifup -a
	/sbin/ifconfig eth0 up
	;;
  stop)
	echo -n "Stopping network..."
	/sbin/ifdown -a
	/sbin/ifconfig eth0 down
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

